### ISSUE TITLE
［error］“afunix.h”: No such file or directory	sc_socket_test	

### ISSUE THREAD

**Issue by ShiverZm** [tezc/sc#72]
![image](https://user-images.githubusercontent.com/26861023/115488023-6b0bf900-a28c-11eb-8ec6-e712e86474fe.png)
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1083	无法打开包括文件: “afunix.h”: No such file or directory	sc_socket_test	F:\workspace\project\github\cpp\sc\socket\sc_sock.c	43	
错误	C1083	无法打开包括文件: “afunix.h”: No such file or directory	sc_socket_test	F:\workspace\project\github\cpp\sc\socket\sc_sock.c	43

**Comment by tezc** [comment]
Thanks for the report @ShiverZm 

AF_UNIX support has been added to Windows three years ago, Windows 10 April 2018 update has it.

If you are using an older Windows version, probably it doesn't have it. I have no intention to support older Windows versions.

1 - If you can, you can try to update Windows to that April 2018 update.
2- Or you can disable AF_UNIX sections in sc_sock.c with "#ifdef _WIN32" s.

**Comment by tezc** [comment]
Closing for now as I have no intention to support older Windows versions. 

Feel free to post if you have any suggestions.
