### ISSUE TITLE
sc_array.h: error: implicit declaration of function 'memmove'

### ISSUE THREAD

**Issue by jpgpng** [tezc/sc#92]
The compiler is MinGW-W64 GCC 11.2 and I cloned directly from github.

**Comment by tezc** [comment]
@jpgpng Thanks for the report. Does this fix the warning?: https://github.com/tezc/sc/pull/93

Looks like mingw `memory.h` does not have `memmove()` in it.

**Comment by jpgpng** [comment]
> @jpgpng Thanks for the report. Does this fix the warning?: #93
> 
> Looks like mingw `memory.h` does not have `memmove()` in it.

Yes, this fixed the compilation of that particular source file.

**Comment by tezc** [comment]
Fixed by https://github.com/tezc/sc/pull/93
